from .activate import *
from .forgot_password import *
from .login import *
from .logout import *
from .profile import *
from .register import *
from .reset_password import *
from .update_address import *
from .update_user import *
